/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see legal.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[1],{341:function(ha,ca,f){function ba(e){e.ya();e.advance();var f=e.current.textContent;e.Ra();return f}function da(e){var f=[];for(e.ya();e.advance();){var h=e.Ga();"field"===h?f.push(String(e.V("name"))):Object(ia.g)("unrecognised field list element: "+h)}e.Ra();return f}function fa(e,f){return f?"false"===e?!1:!0:"true"===e?!0:!1}function z(e,f){var h=e.Ga();switch(h){case "javascript":return{name:"JavaScript",javascript:e.current.textContent};
case "uri":return{name:"URI",uri:e.V("uri")};case "goto":h=null;e.ya();if(e.advance()){var n=e.V("fit");h={page:e.V("page"),fit:n};if("0"===h.page)Object(ia.g)("null page encountered in dest");else switch(f=f(Number(h.page)),n){case "Fit":case "FitB":break;case "FitH":case "FitBH":h.top=f.ha({x:0,y:e.V("top")||0}).y;break;case "FitV":case "FitBV":h.left=f.ha({x:e.V("left")||0,y:0}).x;break;case "FitR":n=f.ha({x:e.V("left")||0,y:e.V("top")||0});f=f.ha({x:e.V("right")||0,y:e.V("bottom")||0});f=new pa.a(n.x,
n.y,f.x,f.y);h.top=f.aa;h.left=f.ea;h.bottom=f.ca;h.right=f.fa;break;case "XYZ":n=f.ha({x:e.V("left")||0,y:e.V("top")||0});h.top=n.y;h.left=n.x;h.zoom=e.V("zoom")||0;break;default:Object(ia.g)("unknown dest fit: "+n)}h={name:"GoTo",dest:h}}else Object(ia.g)("missing dest in GoTo action");e.Ra();return h;case "submit-form":h={name:"SubmitForm",url:e.V("url"),format:e.V("format"),method:e.V("method")||"POST",exclude:fa(e.V("exclude"),!1)};f=e.V("flags");h.flags=f?f.split(" "):[];for(e.ya();e.advance();)switch(f=
e.Ga(),f){case "fields":h.fields=da(e);break;default:Object(ia.g)("unrecognised submit-form child: "+f)}e.Ra();return h;case "reset-form":h={name:"ResetForm",exclude:fa(e.V("exclude"),!1)};for(e.ya();e.advance();)switch(f=e.Ga(),f){case "fields":h.fields=da(e);break;default:Object(ia.g)("unrecognised reset-form child: "+f)}e.Ra();return h;case "hide":h={name:"Hide",hide:fa(e.V("hide"),!0)};for(e.ya();e.advance();)switch(f=e.Ga(),f){case "fields":h.fields=da(e);break;default:Object(ia.g)("unrecognised hide child: "+
f)}e.Ra();return h;case "named":return{name:"Named",action:e.V("name")};default:Object(ia.g)("Encountered unexpected action type: "+h)}return null}function y(e,f,h){var n={};for(e.ya();e.advance();){var r=e.Ga();switch(r){case "action":r=e.V("trigger");if(f?-1!==f.indexOf(r):1){n[r]=[];for(e.ya();e.advance();){var w=z(e,h);Object(ka.isNull)(w)||n[r].push(w)}e.Ra()}else Object(ia.g)("encountered unexpected trigger on field: "+r);break;default:Object(ia.g)("encountered unknown action child: "+r)}}e.Ra();
return n}function x(e){return new oa.a(e.V("r")||0,e.V("g")||0,e.V("b")||0,e.V("a")||1)}function w(e,f){var h=e.V("name"),n=e.V("type")||"Type1",r=e.V("size"),w=f.ha({x:0,y:0});r=f.ha({x:Number(r),y:0});f=w.x-r.x;w=w.y-r.y;h={name:h,type:n,size:Math.sqrt(f*f+w*w)||0,strokeColor:[0,0,0],fillColor:[0,0,0]};for(e.ya();e.advance();)switch(n=e.Ga(),n){case "stroke-color":h.strokeColor=x(e);break;case "fill-color":h.fillColor=x(e);break;default:Object(ia.g)("unrecognised font child: "+n)}e.Ra();return h}
function r(e){return{value:e.V("value"),displayValue:e.V("display-value")||void 0}}function h(e){var f=[];for(e.ya();e.advance();){var h=e.Ga();switch(h){case "option":f.push(r(e));break;default:Object(ia.g)("unrecognised options child: "+h)}}e.Ra();return f}function n(e,f){var n=e.V("name"),r={type:e.V("type"),quadding:e.V("quadding")||"Left-justified",maxLen:e.V("max-len")||-1},x=e.V("flags");Object(ka.isString)(x)&&(r.flags=x.split(" "));for(e.ya();e.advance();)switch(x=e.Ga(),x){case "actions":r.actions=
y(e,["C","F","K","V"],function(){return f});break;case "default-value":r.defaultValue=ba(e);break;case "font":r.font=w(e,f);break;case "options":r.options=h(e);break;default:Object(ia.g)("unknown field child: "+x)}e.Ra();return new window.Annotations.da.ka(n,r)}function e(e,f){switch(e.type){case "Tx":try{if(Object(va.c)(e.actions))return new na.a.DatePickerWidgetAnnotation(e,f)}catch(xa){Object(ia.g)(xa)}return new na.a.TextWidgetAnnotation(e,f);case "Ch":return e.flags.get("Combo")?new na.a.ChoiceWidgetAnnotation(e,
f):new na.a.ListWidgetAnnotation(e,f);case "Btn":return e.flags.get("PushButton")?new na.a.PushButtonWidgetAnnotation(e,f):e.flags.get("Radio")?new na.a.RadioButtonWidgetAnnotation(e,f):new na.a.CheckButtonWidgetAnnotation(e,f);case "Sig":return new na.a.SignatureWidgetAnnotation(e,f);default:Object(ia.g)("Unrecognised field type: "+e.type)}return null}function ea(e,f){var h={number:e.V("number")};for(e.ya();e.advance();){var n=e.Ga();switch(n){case "actions":h.actions=y(e,["O","C"],f);break;default:Object(ia.g)("unrecognised page child: "+
n)}}e.Ra();return h}function aa(f,h,r,z){var aa=[],ba={};f.ya();var ca=[],fa={},ja=[];Object(ma.a)(function(){if(f.advance()){var r=f.Ga();switch(r){case "calculation-order":ca="calculation-order"===f.Ga()?da(f):[];break;case "document-actions":fa=y(f,["Init","Open"],h);break;case "pages":r=[];for(f.ya();f.advance();){var z=f.Ga();switch(z){case "page":r.push(ea(f,h));break;default:Object(ia.g)("unrecognised page child: "+z)}}f.Ra();ja=r;break;case "field":z=n(f,h(1));ba[z.name]=z;break;case "widget":r=
{border:{style:"Solid",width:1},backgroundColor:[],fieldName:f.V("field"),page:f.V("page"),index:f.V("index")||0,rotation:f.V("rotation")||0,flags:[]};(z=f.V("appearance"))&&(r.appearance=z);(z=f.V("flags"))&&(r.flags=z.split(" "));for(f.ya();f.advance();)switch(z=f.Ga(),z){case "rect":var ha=f,la=h(Number(r.page));z=la.ha({x:ha.V("x1")||0,y:ha.V("y1")||0});ha=la.ha({x:ha.V("x2")||0,y:ha.V("y2")||0});z=new pa.a(z.x,z.y,ha.x,ha.y);z.normalize();r.rect={x1:z.x1,y1:z.y1,x2:z.x2,y2:z.y2};break;case "border":z=
f;ha={style:z.V("style")||"Solid",width:z.V("width")||1,color:[0,0,0]};for(z.ya();z.advance();)switch(la=z.Ga(),la){case "color":ha.color=x(z);break;default:Object(ia.g)("unrecognised border child: "+la)}z.Ra();r.border=ha;break;case "background-color":r.backgroundColor=x(f);break;case "actions":r.actions=y(f,"E X D U Fo Bl PO PC PV PI".split(" "),h);break;case "appearances":z=f;ha=Object(va.b)(r,"appearances");for(z.ya();z.advance();)if(la=z.Ga(),"appearance"===la){la=z.V("name");var ka=Object(va.b)(ha,
la);la=z;for(la.ya();la.advance();){var ya=la.Ga();switch(ya){case "Normal":Object(va.b)(ka,"Normal").data=la.current.textContent;break;default:Object(ia.g)("unexpected appearance state: ",ya)}}la.Ra()}else Object(ia.g)("unexpected appearances child: "+la);z.Ra();break;case "extra":z=f;ha=h;la={};for(z.ya();z.advance();)switch(ka=z.Ga(),ka){case "font":la.font=w(z,ha(1));break;default:Object(ia.g)("unrecognised extra child: "+ka)}z.Ra();z=la;z.font&&(r.font=z.font);break;case "captions":ha=f;z={};
(la=ha.V("Normal"))&&(z.Normal=la);(la=ha.V("Rollover"))&&(z.Rollover=la);(ha=ha.V("Down"))&&(z.Down=ha);r.captions=z;break;default:Object(ia.g)("unrecognised widget child: "+z)}f.Ra();(z=ba[r.fieldName])?(r=e(z,r),aa.push(r)):Object(ia.g)("ignoring widget with no corresponding field data: "+r.fieldName);break;default:Object(ia.g)("Unknown element encountered in PDFInfo: "+r)}return!0}return!1},function(){f.Ra();r({calculationOrder:ca,widgets:aa,fields:ba,documentActions:fa,pages:ja,custom:[]})},
z)}f.r(ca);f.d(ca,"parse",function(){return aa});var ia=f(1),ka=f(0);f.n(ka);var na=f(92),pa=f(8),oa=f(7),ma=f(98),va=f(81)}}]);}).call(this || window)
