/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see legal.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[2],{343:function(ha,ca,f){f.r(ca);var ba=f(352),da=f(90),fa=f(31),z=f(55);ha=function(){function f(){this.jb=this.Xd=this.xb=this.Lb=null;this.je=!1}f.prototype.clear=function(){Object(fa.b)(this.Lb);this.xb="";Object(fa.b)(this.Xd);Object(fa.b)(this.jb);this.je=!1};f.prototype.qc=function(){this.Lb=[];this.Xd=[];this.jb=[];this.je=!1};f.prototype.ju=function(f){for(var w="",r=0,h,n,e;r<f.length;)h=f.charCodeAt(r),9==h?(w+=String.fromCharCode(10),
r++):128>h?(w+=String.fromCharCode(h),r++):191<h&&224>h?(n=f.charCodeAt(r+1),w+=String.fromCharCode((h&31)<<6|n&63),r+=2):(n=f.charCodeAt(r+1),e=f.charCodeAt(r+2),w+=String.fromCharCode((h&15)<<12|(n&63)<<6|e&63),r+=3);return w};f.prototype.initData=function(f){this.Lb=[];this.Xd=[];this.jb=[];this.je=!1;try{var w=new z.a(f);this.xb="";w.ya();if(!w.advance())return;var r=w.current.textContent;this.xb=r=this.ju(r);Object(fa.b)(this.Xd);w.advance();r=w.current.textContent;for(var h=r.split(","),n=Object(da.a)(h);n.Cj();){var e=
n.current;try{var x=parseInt(e.trim());this.Xd.push(x)}catch(la){}}Object(fa.b)(this.Lb);w.advance();r=w.current.textContent;h=r.split(",");for(var y=Object(da.a)(h);y.Cj();){e=y.current;try{x=parseFloat(e.trim()),this.Lb.push(x)}catch(la){}}Object(fa.b)(this.jb);w.advance();r=w.current.textContent;h=r.split(",");f=[];w=[];r=0;for(var ba=Object(da.a)(h);ba.Cj();){e=ba.current;switch(e){case "Q":r=1;break;case "R":r=2;break;case "S":r=3;break;default:r=0}if(r)f.push(0),w.push(r);else try{x=parseFloat(e.trim()),
f.push(x),w.push(r)}catch(la){return}}r=0;var ca=f.length;for(ba=e=h=0;ba<ca;){var ha=w[ba];if(0<ha)r=ha,++ba,3===r&&(h=f[ba],e=f[ba+1],ba+=2);else if(1===r)for(x=0;8>x;++x)this.jb.push(f[ba++]);else if(2===r){var pa=f[ba++];var oa=f[ba++];var ma=f[ba++];var va=f[ba++];this.jb.push(pa);this.jb.push(oa);this.jb.push(ma);this.jb.push(oa);this.jb.push(ma);this.jb.push(va);this.jb.push(pa);this.jb.push(va)}else 3===r&&(pa=f[ba++],oa=h,ma=f[ba++],va=e,this.jb.push(pa),this.jb.push(oa),this.jb.push(ma),
this.jb.push(oa),this.jb.push(ma),this.jb.push(va),this.jb.push(pa),this.jb.push(va))}}catch(la){return}this.xb.length&&this.xb.length===this.Xd.length&&8*this.xb.length===this.jb.length&&(this.je=!0)};f.prototype.ready=function(){return this.je};f.prototype.Kr=function(){var f=new ba.a;if(!this.Lb.length)return f.Tf(this.Lb,-1,this.xb,this.jb,0),f;f.Tf(this.Lb,1,this.xb,this.jb,1);return f};f.prototype.Ue=function(){return this.jb};f.prototype.getData=function(){return{m_Struct:this.Lb,m_Str:this.xb,
m_Offsets:this.Xd,m_Quads:this.jb,m_Ready:this.je}};return f}();ca["default"]=ha},352:function(ha,ca,f){var ba=f(53),da=f(197),fa=f(364);ha=function(){function f(){this.Cd=0;this.ab=this.ta=this.re=null;this.lc=0;this.Bd=null}f.prototype.qc=function(){this.Cd=-1;this.lc=0;this.Bd=[]};f.prototype.Tf=function(f,x,w,r,h){this.Cd=x;this.lc=h;this.Bd=[];this.re=f;this.ta=w;this.ab=r};f.prototype.Fa=function(f){return this.Cd===f.Cd};f.prototype.Uh=function(){return Math.abs(this.re[this.Cd])};f.prototype.Aj=
function(){return 0<this.re[this.Cd]};f.prototype.zc=function(){var f=this.Aj()?6:10,x=new fa.a;x.Tf(this.re,this.Cd+f,this.Cd,this.ta,this.ab,1);return x};f.prototype.xJ=function(f){if(0>f||f>=this.Uh()){var x=new fa.a;x.Tf(this.re,-1,-1,this.ta,this.ab,0);return x}var w=this.Aj()?6:10,r=this.Aj()?5:11;x=new fa.a;x.Tf(this.re,this.Cd+w+r*f,this.Cd,this.ta,this.ab,1+f);return x};f.prototype.uf=function(){var y=this.Cd+parseInt(this.re[this.Cd+1]);if(y>=this.re.length){var x=new f;x.Tf(this.re,-1,
this.ta,this.ab,0);return x}x=new f;x.Tf(this.re,y,this.ta,this.ab,this.lc+1);return x};f.prototype.Zb=function(f){if(this.Aj())f.ea=this.re[this.Cd+2+0],f.aa=this.re[this.Cd+2+1],f.fa=this.re[this.Cd+2+2],f.ca=this.re[this.Cd+2+3];else{for(var x=1.79769E308,w=ba.a.MIN,r=1.79769E308,h=ba.a.MIN,n=0;4>n;++n){var e=this.re[this.Cd+2+2*n],y=this.re[this.Cd+2+2*n+1];x=Math.min(x,e);w=Math.max(w,e);r=Math.min(r,y);h=Math.max(h,y)}f.ea=x;f.aa=r;f.fa=w;f.ca=h}};f.prototype.Th=function(){if(this.Bd.length)return this.Bd[0];
var f=new da.a,x=new da.a,w=new fa.a;w.qc();var r=this.zc(),h=new fa.a;h.qc();for(var n=this.zc();!n.Fa(w);n=n.Se())h=n;w=Array(8);n=Array(8);r.ge(0,w);f.x=(w[0]+w[2]+w[4]+w[6])/4;f.y=(w[1]+w[3]+w[5]+w[7])/4;h.ge(h.Rc()-1,n);x.x=(n[0]+n[2]+n[4]+n[6])/4;x.y=(n[1]+n[3]+n[5]+n[7])/4;.01>Math.abs(f.x-x.x)&&.01>Math.abs(f.y-x.y)&&this.Bd.push(0);f=Math.atan2(x.y-f.y,x.x-f.x);f*=180/3.1415926;0>f&&(f+=360);this.Bd.push(f);return 0};return f}();ca.a=ha},364:function(ha,ca,f){var ba=f(352),da=f(108),fa=f(53);
ha=function(){function f(){this.Di=this.ed=0;this.ab=this.ta=this.Lb=null;this.lc=0}f.prototype.qc=function(){this.Di=this.ed=-1;this.lc=0};f.prototype.Tf=function(f,x,w,r,h,n){this.ed=x;this.Di=w;this.Lb=f;this.ta=r;this.ab=h;this.lc=n};f.prototype.Fa=function(f){return this.ed===f.ed};f.prototype.Rc=function(){return parseInt(this.Lb[this.ed])};f.prototype.Zg=function(){return parseInt(this.Lb[this.ed+2])};f.prototype.Bb=function(){return parseInt(this.Lb[this.ed+1])};f.prototype.Aj=function(){return 0<
this.Lb[this.Di]};f.prototype.qV=function(){return Math.abs(this.Lb[this.Di])};f.prototype.Se=function(){var y=this.Aj(),x=y?5:11;if(this.ed>=this.Di+(y?6:10)+(this.qV()-1)*x)return y=new f,y.Tf(this.Lb,-1,-1,this.ta,this.ab,0),y;y=new f;y.Tf(this.Lb,this.ed+x,this.Di,this.ta,this.ab,this.lc+1);return y};f.prototype.RU=function(f){var x=this.Rc();return 0>f||f>=x?-1:parseInt(this.Lb[this.ed+1])+f};f.prototype.ge=function(f,x){f=this.RU(f);if(!(0>f)){var w=new ba.a;w.Tf(this.Lb,this.Di,this.ta,this.ab,
0);if(w.Aj()){var r=new da.a;w.Zb(r);w=r.aa<r.ca?r.aa:r.ca;r=r.aa>r.ca?r.aa:r.ca;f*=8;x[0]=this.ab[f];x[1]=w;x[2]=this.ab[f+2];x[3]=x[1];x[4]=this.ab[f+4];x[5]=r;x[6]=this.ab[f+6];x[7]=x[5]}else for(f*=8,w=0;8>w;++w)x[w]=this.ab[f+w]}};f.prototype.Ed=function(f){var x=new ba.a;x.Tf(this.Lb,this.Di,this.ta,this.ab,0);if(x.Aj()){var w=this.Lb[this.ed+3],r=this.Lb[this.ed+4];if(w>r){var h=w;w=r;r=h}h=new da.a;x.Zb(h);x=h.aa<h.ca?h.aa:h.ca;h=h.aa>h.ca?h.aa:h.ca;f[0]=w;f[1]=x;f[2]=r;f[3]=x;f[4]=r;f[5]=
h;f[6]=w;f[7]=h}else for(w=this.ed+3,r=0;8>r;++r)f[r]=this.Lb[w+r]};f.prototype.Zb=function(f){var x=new ba.a;x.Tf(this.Lb,this.Di,this.ta,this.ab,0);if(x.Aj()){var w=this.Lb[this.ed+3],r=this.Lb[this.ed+4];if(w>r){var h=w;w=r;r=h}h=new da.a;x.Zb(h);x=h.aa<h.ca?h.aa:h.ca;h=h.aa>h.ca?h.aa:h.ca;f[0]=w;f[1]=x;f[2]=r;f[3]=h}else{w=1.79769E308;r=fa.a.MIN;x=1.79769E308;h=fa.a.MIN;for(var n=this.ed+3,e=0;4>e;++e){var y=this.Lb[n+2*e],z=this.Lb[n+2*e+1];w=Math.min(w,y);r=Math.max(r,y);x=Math.min(x,z);h=Math.max(h,
z)}f[0]=w;f[1]=x;f[2]=r;f[3]=h}};return f}();ca.a=ha}}]);}).call(this || window)
